### ISSUE TITLE
Licenced not specified

### ISSUE THREAD

**Issue by SteveALee** [ayelet-seeman/coga.personalisation#7]

**Comment by lseeman** [comment]
I think it was specified recently I will check this

All the best

Lisa Seeman

LinkedIn, Twitter





---- On Tue, 24 Jan 2017 13:52:53 +0200 Steve Lee&lt;notifications@github.com&gt; wrote ----

**Comment by SteveALee** [comment]
to clarify - there's no LICENSE file

**Comment by inclusiveThinking** [comment]
What is the licensing language we use?

**Comment by lseeman** [comment]
I had understood it was there. if not we can add the MIT licensehttps://opensource.org/licenses/MIT


or we can use the gnu one


All the best

Lisa Seeman

LinkedIn, Twitter





---- On Wed, 08 Feb 2017 05:04:48 +0200 Thaddeus&lt;notifications@github.com&gt; wrote ---- 

What is the licensing language we use?

**Comment by inclusiveThinking** [comment]
Thanks. I just updated my local version with the MIT license

**Comment by lseeman** [comment]
MIT liecence is added here too
